/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLifersRouteImport } from './routes/_authenticated/lifers'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedApeRidesRouteImport } from './routes/_authenticated/ape-rides'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLifersIndexRouteImport } from './routes/_authenticated/lifers/index'
import { Route as AuthenticatedRoomsRoomIdRouteImport } from './routes/_authenticated/rooms.$roomId'
import { Route as AuthenticatedLifersRoomRouteImport } from './routes/_authenticated/lifers/room'
import { Route as AuthenticatedLifersMessagesRouteImport } from './routes/_authenticated/lifers/messages'
import { Route as AuthenticatedApeRidesRideIdRouteImport } from './routes/_authenticated/ape-rides.$rideId'
import { Route as AuthenticatedAdminOtherpageRouteImport } from './routes/_authenticated/admin.otherpage'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLifersRoute = AuthenticatedLifersRouteImport.update({
  id: '/lifers',
  path: '/lifers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApeRidesRoute = AuthenticatedApeRidesRouteImport.update({
  id: '/ape-rides',
  path: '/ape-rides',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLifersIndexRoute =
  AuthenticatedLifersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLifersRoute,
  } as any)
const AuthenticatedRoomsRoomIdRoute =
  AuthenticatedRoomsRoomIdRouteImport.update({
    id: '/$roomId',
    path: '/$roomId',
    getParentRoute: () => AuthenticatedRoomsRoute,
  } as any)
const AuthenticatedLifersRoomRoute = AuthenticatedLifersRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AuthenticatedLifersRoute,
} as any)
const AuthenticatedLifersMessagesRoute =
  AuthenticatedLifersMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedLifersRoute,
  } as any)
const AuthenticatedApeRidesRideIdRoute =
  AuthenticatedApeRidesRideIdRouteImport.update({
    id: '/$rideId',
    path: '/$rideId',
    getParentRoute: () => AuthenticatedApeRidesRoute,
  } as any)
const AuthenticatedAdminOtherpageRoute =
  AuthenticatedAdminOtherpageRouteImport.update({
    id: '/otherpage',
    path: '/otherpage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ape-rides': typeof AuthenticatedApeRidesRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/lifers': typeof AuthenticatedLifersRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/ape-rides/$rideId': typeof AuthenticatedApeRidesRideIdRoute
  '/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/lifers/': typeof AuthenticatedLifersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ape-rides': typeof AuthenticatedApeRidesRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/ape-rides/$rideId': typeof AuthenticatedApeRidesRideIdRoute
  '/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/lifers': typeof AuthenticatedLifersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ape-rides': typeof AuthenticatedApeRidesRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/lifers': typeof AuthenticatedLifersRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/_authenticated/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/_authenticated/ape-rides/$rideId': typeof AuthenticatedApeRidesRideIdRoute
  '/_authenticated/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/_authenticated/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/_authenticated/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/_authenticated/lifers/': typeof AuthenticatedLifersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ape-rides'
    | '/feed'
    | '/lifers'
    | '/messages'
    | '/profile'
    | '/rooms'
    | '/admin/otherpage'
    | '/ape-rides/$rideId'
    | '/lifers/messages'
    | '/lifers/room'
    | '/rooms/$roomId'
    | '/lifers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ape-rides'
    | '/feed'
    | '/messages'
    | '/profile'
    | '/rooms'
    | '/admin/otherpage'
    | '/ape-rides/$rideId'
    | '/lifers/messages'
    | '/lifers/room'
    | '/rooms/$roomId'
    | '/lifers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/ape-rides'
    | '/_authenticated/feed'
    | '/_authenticated/lifers'
    | '/_authenticated/messages'
    | '/_authenticated/profile'
    | '/_authenticated/rooms'
    | '/_authenticated/admin/otherpage'
    | '/_authenticated/ape-rides/$rideId'
    | '/_authenticated/lifers/messages'
    | '/_authenticated/lifers/room'
    | '/_authenticated/rooms/$roomId'
    | '/_authenticated/lifers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lifers': {
      id: '/_authenticated/lifers'
      path: '/lifers'
      fullPath: '/lifers'
      preLoaderRoute: typeof AuthenticatedLifersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ape-rides': {
      id: '/_authenticated/ape-rides'
      path: '/ape-rides'
      fullPath: '/ape-rides'
      preLoaderRoute: typeof AuthenticatedApeRidesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lifers/': {
      id: '/_authenticated/lifers/'
      path: '/'
      fullPath: '/lifers/'
      preLoaderRoute: typeof AuthenticatedLifersIndexRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/rooms/$roomId': {
      id: '/_authenticated/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoomsRoute
    }
    '/_authenticated/lifers/room': {
      id: '/_authenticated/lifers/room'
      path: '/room'
      fullPath: '/lifers/room'
      preLoaderRoute: typeof AuthenticatedLifersRoomRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/lifers/messages': {
      id: '/_authenticated/lifers/messages'
      path: '/messages'
      fullPath: '/lifers/messages'
      preLoaderRoute: typeof AuthenticatedLifersMessagesRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/ape-rides/$rideId': {
      id: '/_authenticated/ape-rides/$rideId'
      path: '/$rideId'
      fullPath: '/ape-rides/$rideId'
      preLoaderRoute: typeof AuthenticatedApeRidesRideIdRouteImport
      parentRoute: typeof AuthenticatedApeRidesRoute
    }
    '/_authenticated/admin/otherpage': {
      id: '/_authenticated/admin/otherpage'
      path: '/otherpage'
      fullPath: '/admin/otherpage'
      preLoaderRoute: typeof AuthenticatedAdminOtherpageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOtherpageRoute: typeof AuthenticatedAdminOtherpageRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOtherpageRoute: AuthenticatedAdminOtherpageRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedApeRidesRouteChildren {
  AuthenticatedApeRidesRideIdRoute: typeof AuthenticatedApeRidesRideIdRoute
}

const AuthenticatedApeRidesRouteChildren: AuthenticatedApeRidesRouteChildren = {
  AuthenticatedApeRidesRideIdRoute: AuthenticatedApeRidesRideIdRoute,
}

const AuthenticatedApeRidesRouteWithChildren =
  AuthenticatedApeRidesRoute._addFileChildren(
    AuthenticatedApeRidesRouteChildren,
  )

interface AuthenticatedLifersRouteChildren {
  AuthenticatedLifersMessagesRoute: typeof AuthenticatedLifersMessagesRoute
  AuthenticatedLifersRoomRoute: typeof AuthenticatedLifersRoomRoute
  AuthenticatedLifersIndexRoute: typeof AuthenticatedLifersIndexRoute
}

const AuthenticatedLifersRouteChildren: AuthenticatedLifersRouteChildren = {
  AuthenticatedLifersMessagesRoute: AuthenticatedLifersMessagesRoute,
  AuthenticatedLifersRoomRoute: AuthenticatedLifersRoomRoute,
  AuthenticatedLifersIndexRoute: AuthenticatedLifersIndexRoute,
}

const AuthenticatedLifersRouteWithChildren =
  AuthenticatedLifersRoute._addFileChildren(AuthenticatedLifersRouteChildren)

interface AuthenticatedRoomsRouteChildren {
  AuthenticatedRoomsRoomIdRoute: typeof AuthenticatedRoomsRoomIdRoute
}

const AuthenticatedRoomsRouteChildren: AuthenticatedRoomsRouteChildren = {
  AuthenticatedRoomsRoomIdRoute: AuthenticatedRoomsRoomIdRoute,
}

const AuthenticatedRoomsRouteWithChildren =
  AuthenticatedRoomsRoute._addFileChildren(AuthenticatedRoomsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedApeRidesRoute: typeof AuthenticatedApeRidesRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedLifersRoute: typeof AuthenticatedLifersRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedApeRidesRoute: AuthenticatedApeRidesRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedLifersRoute: AuthenticatedLifersRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
