/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLifersRouteImport } from './routes/_authenticated/lifers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVerifiedRouteImport } from './routes/_authenticated/_verified'
import { Route as AuthenticatedLifersIndexRouteImport } from './routes/_authenticated/lifers/index'
import { Route as AuthenticatedLifersRoomRouteImport } from './routes/_authenticated/lifers/room'
import { Route as AuthenticatedLifersMessagesRouteImport } from './routes/_authenticated/lifers/messages'
import { Route as AuthenticatedAdminOtherpageRouteImport } from './routes/_authenticated/admin.otherpage'
import { Route as AuthenticatedAdminLuminaRouteImport } from './routes/_authenticated/admin.lumina'
import { Route as AuthenticatedVerifiedRoomsRouteImport } from './routes/_authenticated/_verified/rooms'
import { Route as AuthenticatedVerifiedMessagesRouteImport } from './routes/_authenticated/_verified/messages'
import { Route as AuthenticatedVerifiedFeedRouteImport } from './routes/_authenticated/_verified/feed'
import { Route as AuthenticatedVerifiedApeRidesRouteImport } from './routes/_authenticated/_verified/ape-rides'
import { Route as AuthenticatedVerifiedRoomsRoomIdRouteImport } from './routes/_authenticated/_verified/rooms.$roomId'
import { Route as AuthenticatedVerifiedApeRidesRideIdRouteImport } from './routes/_authenticated/_verified/ape-rides.$rideId'

const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLifersRoute = AuthenticatedLifersRouteImport.update({
  id: '/lifers',
  path: '/lifers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVerifiedRoute = AuthenticatedVerifiedRouteImport.update({
  id: '/_verified',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLifersIndexRoute =
  AuthenticatedLifersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLifersRoute,
  } as any)
const AuthenticatedLifersRoomRoute = AuthenticatedLifersRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AuthenticatedLifersRoute,
} as any)
const AuthenticatedLifersMessagesRoute =
  AuthenticatedLifersMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedLifersRoute,
  } as any)
const AuthenticatedAdminOtherpageRoute =
  AuthenticatedAdminOtherpageRouteImport.update({
    id: '/otherpage',
    path: '/otherpage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLuminaRoute =
  AuthenticatedAdminLuminaRouteImport.update({
    id: '/lumina',
    path: '/lumina',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedVerifiedRoomsRoute =
  AuthenticatedVerifiedRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedMessagesRoute =
  AuthenticatedVerifiedMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedFeedRoute =
  AuthenticatedVerifiedFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedApeRidesRoute =
  AuthenticatedVerifiedApeRidesRouteImport.update({
    id: '/ape-rides',
    path: '/ape-rides',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedRoomsRoomIdRoute =
  AuthenticatedVerifiedRoomsRoomIdRouteImport.update({
    id: '/$roomId',
    path: '/$roomId',
    getParentRoute: () => AuthenticatedVerifiedRoomsRoute,
  } as any)
const AuthenticatedVerifiedApeRidesRideIdRoute =
  AuthenticatedVerifiedApeRidesRideIdRouteImport.update({
    id: '/$rideId',
    path: '/$rideId',
    getParentRoute: () => AuthenticatedVerifiedApeRidesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/lifers': typeof AuthenticatedLifersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/ape-rides': typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  '/feed': typeof AuthenticatedVerifiedFeedRoute
  '/messages': typeof AuthenticatedVerifiedMessagesRoute
  '/rooms': typeof AuthenticatedVerifiedRoomsRouteWithChildren
  '/admin/lumina': typeof AuthenticatedAdminLuminaRoute
  '/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/lifers/': typeof AuthenticatedLifersIndexRoute
  '/ape-rides/$rideId': typeof AuthenticatedVerifiedApeRidesRideIdRoute
  '/rooms/$roomId': typeof AuthenticatedVerifiedRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/ape-rides': typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  '/feed': typeof AuthenticatedVerifiedFeedRoute
  '/messages': typeof AuthenticatedVerifiedMessagesRoute
  '/rooms': typeof AuthenticatedVerifiedRoomsRouteWithChildren
  '/admin/lumina': typeof AuthenticatedAdminLuminaRoute
  '/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/lifers': typeof AuthenticatedLifersIndexRoute
  '/ape-rides/$rideId': typeof AuthenticatedVerifiedApeRidesRideIdRoute
  '/rooms/$roomId': typeof AuthenticatedVerifiedRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/diagnostics': typeof DiagnosticsRoute
  '/_authenticated/_verified': typeof AuthenticatedVerifiedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/lifers': typeof AuthenticatedLifersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/_verified/ape-rides': typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  '/_authenticated/_verified/feed': typeof AuthenticatedVerifiedFeedRoute
  '/_authenticated/_verified/messages': typeof AuthenticatedVerifiedMessagesRoute
  '/_authenticated/_verified/rooms': typeof AuthenticatedVerifiedRoomsRouteWithChildren
  '/_authenticated/admin/lumina': typeof AuthenticatedAdminLuminaRoute
  '/_authenticated/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/_authenticated/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/_authenticated/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/_authenticated/lifers/': typeof AuthenticatedLifersIndexRoute
  '/_authenticated/_verified/ape-rides/$rideId': typeof AuthenticatedVerifiedApeRidesRideIdRoute
  '/_authenticated/_verified/rooms/$roomId': typeof AuthenticatedVerifiedRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/admin'
    | '/lifers'
    | '/profile'
    | '/ape-rides'
    | '/feed'
    | '/messages'
    | '/rooms'
    | '/admin/lumina'
    | '/admin/otherpage'
    | '/lifers/messages'
    | '/lifers/room'
    | '/lifers/'
    | '/ape-rides/$rideId'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/admin'
    | '/profile'
    | '/ape-rides'
    | '/feed'
    | '/messages'
    | '/rooms'
    | '/admin/lumina'
    | '/admin/otherpage'
    | '/lifers/messages'
    | '/lifers/room'
    | '/lifers'
    | '/ape-rides/$rideId'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/diagnostics'
    | '/_authenticated/_verified'
    | '/_authenticated/admin'
    | '/_authenticated/lifers'
    | '/_authenticated/profile'
    | '/_authenticated/_verified/ape-rides'
    | '/_authenticated/_verified/feed'
    | '/_authenticated/_verified/messages'
    | '/_authenticated/_verified/rooms'
    | '/_authenticated/admin/lumina'
    | '/_authenticated/admin/otherpage'
    | '/_authenticated/lifers/messages'
    | '/_authenticated/lifers/room'
    | '/_authenticated/lifers/'
    | '/_authenticated/_verified/ape-rides/$rideId'
    | '/_authenticated/_verified/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DiagnosticsRoute: typeof DiagnosticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lifers': {
      id: '/_authenticated/lifers'
      path: '/lifers'
      fullPath: '/lifers'
      preLoaderRoute: typeof AuthenticatedLifersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_verified': {
      id: '/_authenticated/_verified'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedVerifiedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lifers/': {
      id: '/_authenticated/lifers/'
      path: '/'
      fullPath: '/lifers/'
      preLoaderRoute: typeof AuthenticatedLifersIndexRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/lifers/room': {
      id: '/_authenticated/lifers/room'
      path: '/room'
      fullPath: '/lifers/room'
      preLoaderRoute: typeof AuthenticatedLifersRoomRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/lifers/messages': {
      id: '/_authenticated/lifers/messages'
      path: '/messages'
      fullPath: '/lifers/messages'
      preLoaderRoute: typeof AuthenticatedLifersMessagesRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/admin/otherpage': {
      id: '/_authenticated/admin/otherpage'
      path: '/otherpage'
      fullPath: '/admin/otherpage'
      preLoaderRoute: typeof AuthenticatedAdminOtherpageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lumina': {
      id: '/_authenticated/admin/lumina'
      path: '/lumina'
      fullPath: '/admin/lumina'
      preLoaderRoute: typeof AuthenticatedAdminLuminaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_verified/rooms': {
      id: '/_authenticated/_verified/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedVerifiedRoomsRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/messages': {
      id: '/_authenticated/_verified/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/feed': {
      id: '/_authenticated/_verified/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedVerifiedFeedRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/ape-rides': {
      id: '/_authenticated/_verified/ape-rides'
      path: '/ape-rides'
      fullPath: '/ape-rides'
      preLoaderRoute: typeof AuthenticatedVerifiedApeRidesRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/rooms/$roomId': {
      id: '/_authenticated/_verified/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedVerifiedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoomsRoute
    }
    '/_authenticated/_verified/ape-rides/$rideId': {
      id: '/_authenticated/_verified/ape-rides/$rideId'
      path: '/$rideId'
      fullPath: '/ape-rides/$rideId'
      preLoaderRoute: typeof AuthenticatedVerifiedApeRidesRideIdRouteImport
      parentRoute: typeof AuthenticatedVerifiedApeRidesRoute
    }
  }
}

interface AuthenticatedVerifiedApeRidesRouteChildren {
  AuthenticatedVerifiedApeRidesRideIdRoute: typeof AuthenticatedVerifiedApeRidesRideIdRoute
}

const AuthenticatedVerifiedApeRidesRouteChildren: AuthenticatedVerifiedApeRidesRouteChildren =
  {
    AuthenticatedVerifiedApeRidesRideIdRoute:
      AuthenticatedVerifiedApeRidesRideIdRoute,
  }

const AuthenticatedVerifiedApeRidesRouteWithChildren =
  AuthenticatedVerifiedApeRidesRoute._addFileChildren(
    AuthenticatedVerifiedApeRidesRouteChildren,
  )

interface AuthenticatedVerifiedRoomsRouteChildren {
  AuthenticatedVerifiedRoomsRoomIdRoute: typeof AuthenticatedVerifiedRoomsRoomIdRoute
}

const AuthenticatedVerifiedRoomsRouteChildren: AuthenticatedVerifiedRoomsRouteChildren =
  {
    AuthenticatedVerifiedRoomsRoomIdRoute:
      AuthenticatedVerifiedRoomsRoomIdRoute,
  }

const AuthenticatedVerifiedRoomsRouteWithChildren =
  AuthenticatedVerifiedRoomsRoute._addFileChildren(
    AuthenticatedVerifiedRoomsRouteChildren,
  )

interface AuthenticatedVerifiedRouteChildren {
  AuthenticatedVerifiedApeRidesRoute: typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  AuthenticatedVerifiedFeedRoute: typeof AuthenticatedVerifiedFeedRoute
  AuthenticatedVerifiedMessagesRoute: typeof AuthenticatedVerifiedMessagesRoute
  AuthenticatedVerifiedRoomsRoute: typeof AuthenticatedVerifiedRoomsRouteWithChildren
}

const AuthenticatedVerifiedRouteChildren: AuthenticatedVerifiedRouteChildren = {
  AuthenticatedVerifiedApeRidesRoute:
    AuthenticatedVerifiedApeRidesRouteWithChildren,
  AuthenticatedVerifiedFeedRoute: AuthenticatedVerifiedFeedRoute,
  AuthenticatedVerifiedMessagesRoute: AuthenticatedVerifiedMessagesRoute,
  AuthenticatedVerifiedRoomsRoute: AuthenticatedVerifiedRoomsRouteWithChildren,
}

const AuthenticatedVerifiedRouteWithChildren =
  AuthenticatedVerifiedRoute._addFileChildren(
    AuthenticatedVerifiedRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLuminaRoute: typeof AuthenticatedAdminLuminaRoute
  AuthenticatedAdminOtherpageRoute: typeof AuthenticatedAdminOtherpageRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLuminaRoute: AuthenticatedAdminLuminaRoute,
  AuthenticatedAdminOtherpageRoute: AuthenticatedAdminOtherpageRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLifersRouteChildren {
  AuthenticatedLifersMessagesRoute: typeof AuthenticatedLifersMessagesRoute
  AuthenticatedLifersRoomRoute: typeof AuthenticatedLifersRoomRoute
  AuthenticatedLifersIndexRoute: typeof AuthenticatedLifersIndexRoute
}

const AuthenticatedLifersRouteChildren: AuthenticatedLifersRouteChildren = {
  AuthenticatedLifersMessagesRoute: AuthenticatedLifersMessagesRoute,
  AuthenticatedLifersRoomRoute: AuthenticatedLifersRoomRoute,
  AuthenticatedLifersIndexRoute: AuthenticatedLifersIndexRoute,
}

const AuthenticatedLifersRouteWithChildren =
  AuthenticatedLifersRoute._addFileChildren(AuthenticatedLifersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedVerifiedRoute: typeof AuthenticatedVerifiedRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLifersRoute: typeof AuthenticatedLifersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedVerifiedRoute: AuthenticatedVerifiedRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLifersRoute: AuthenticatedLifersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DiagnosticsRoute: DiagnosticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
