/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLobbyRouteImport } from './routes/_authenticated/lobby'
import { Route as AuthenticatedLifersRouteImport } from './routes/_authenticated/lifers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedVerifiedRouteImport } from './routes/_authenticated/_verified'
import { Route as AuthenticatedLifersIndexRouteImport } from './routes/_authenticated/lifers/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedLifersRoomRouteImport } from './routes/_authenticated/lifers/room'
import { Route as AuthenticatedLifersMessagesRouteImport } from './routes/_authenticated/lifers/messages'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminOtherpageRouteImport } from './routes/_authenticated/admin.otherpage'
import { Route as AuthenticatedAdminLuminaRouteImport } from './routes/_authenticated/admin.lumina'
import { Route as AuthenticatedAdminKaraokeRouteImport } from './routes/_authenticated/admin.karaoke'
import { Route as AuthenticatedVerifiedRoomsRouteImport } from './routes/_authenticated/_verified/rooms'
import { Route as AuthenticatedVerifiedFeedRouteImport } from './routes/_authenticated/_verified/feed'
import { Route as AuthenticatedVerifiedCalendarRouteImport } from './routes/_authenticated/_verified/calendar'
import { Route as AuthenticatedVerifiedApeRidesRouteImport } from './routes/_authenticated/_verified/ape-rides'
import { Route as AuthenticatedVerifiedRoomsRoomIdRouteImport } from './routes/_authenticated/_verified/rooms_.$roomId'
import { Route as AuthenticatedVerifiedApeRidesRideIdRouteImport } from './routes/_authenticated/_verified/ape-rides.$rideId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLobbyRoute = AuthenticatedLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLifersRoute = AuthenticatedLifersRouteImport.update({
  id: '/lifers',
  path: '/lifers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVerifiedRoute = AuthenticatedVerifiedRouteImport.update({
  id: '/_verified',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLifersIndexRoute =
  AuthenticatedLifersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLifersRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedLifersRoomRoute = AuthenticatedLifersRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AuthenticatedLifersRoute,
} as any)
const AuthenticatedLifersMessagesRoute =
  AuthenticatedLifersMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedLifersRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOtherpageRoute =
  AuthenticatedAdminOtherpageRouteImport.update({
    id: '/otherpage',
    path: '/otherpage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLuminaRoute =
  AuthenticatedAdminLuminaRouteImport.update({
    id: '/lumina',
    path: '/lumina',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKaraokeRoute =
  AuthenticatedAdminKaraokeRouteImport.update({
    id: '/karaoke',
    path: '/karaoke',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedVerifiedRoomsRoute =
  AuthenticatedVerifiedRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedFeedRoute =
  AuthenticatedVerifiedFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedCalendarRoute =
  AuthenticatedVerifiedCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedApeRidesRoute =
  AuthenticatedVerifiedApeRidesRouteImport.update({
    id: '/ape-rides',
    path: '/ape-rides',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedRoomsRoomIdRoute =
  AuthenticatedVerifiedRoomsRoomIdRouteImport.update({
    id: '/rooms_/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AuthenticatedVerifiedRoute,
  } as any)
const AuthenticatedVerifiedApeRidesRideIdRoute =
  AuthenticatedVerifiedApeRidesRideIdRouteImport.update({
    id: '/$rideId',
    path: '/$rideId',
    getParentRoute: () => AuthenticatedVerifiedApeRidesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/lifers': typeof AuthenticatedLifersRouteWithChildren
  '/lobby': typeof AuthenticatedLobbyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/support': typeof AuthenticatedSupportRoute
  '/ape-rides': typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  '/calendar': typeof AuthenticatedVerifiedCalendarRoute
  '/feed': typeof AuthenticatedVerifiedFeedRoute
  '/rooms': typeof AuthenticatedVerifiedRoomsRoute
  '/admin/karaoke': typeof AuthenticatedAdminKaraokeRoute
  '/admin/lumina': typeof AuthenticatedAdminLuminaRoute
  '/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lifers/': typeof AuthenticatedLifersIndexRoute
  '/ape-rides/$rideId': typeof AuthenticatedVerifiedApeRidesRideIdRoute
  '/rooms/$roomId': typeof AuthenticatedVerifiedRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/lobby': typeof AuthenticatedLobbyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/support': typeof AuthenticatedSupportRoute
  '/ape-rides': typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  '/calendar': typeof AuthenticatedVerifiedCalendarRoute
  '/feed': typeof AuthenticatedVerifiedFeedRoute
  '/rooms': typeof AuthenticatedVerifiedRoomsRoute
  '/admin/karaoke': typeof AuthenticatedAdminKaraokeRoute
  '/admin/lumina': typeof AuthenticatedAdminLuminaRoute
  '/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lifers': typeof AuthenticatedLifersIndexRoute
  '/ape-rides/$rideId': typeof AuthenticatedVerifiedApeRidesRideIdRoute
  '/rooms/$roomId': typeof AuthenticatedVerifiedRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/_authenticated/_verified': typeof AuthenticatedVerifiedRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/lifers': typeof AuthenticatedLifersRouteWithChildren
  '/_authenticated/lobby': typeof AuthenticatedLobbyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/_verified/ape-rides': typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  '/_authenticated/_verified/calendar': typeof AuthenticatedVerifiedCalendarRoute
  '/_authenticated/_verified/feed': typeof AuthenticatedVerifiedFeedRoute
  '/_authenticated/_verified/rooms': typeof AuthenticatedVerifiedRoomsRoute
  '/_authenticated/admin/karaoke': typeof AuthenticatedAdminKaraokeRoute
  '/_authenticated/admin/lumina': typeof AuthenticatedAdminLuminaRoute
  '/_authenticated/admin/otherpage': typeof AuthenticatedAdminOtherpageRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/lifers/messages': typeof AuthenticatedLifersMessagesRoute
  '/_authenticated/lifers/room': typeof AuthenticatedLifersRoomRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/lifers/': typeof AuthenticatedLifersIndexRoute
  '/_authenticated/_verified/ape-rides/$rideId': typeof AuthenticatedVerifiedApeRidesRideIdRoute
  '/_authenticated/_verified/rooms_/$roomId': typeof AuthenticatedVerifiedRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/activity'
    | '/admin'
    | '/lifers'
    | '/lobby'
    | '/profile'
    | '/super-admin'
    | '/support'
    | '/ape-rides'
    | '/calendar'
    | '/feed'
    | '/rooms'
    | '/admin/karaoke'
    | '/admin/lumina'
    | '/admin/otherpage'
    | '/admin/support'
    | '/admin/users'
    | '/lifers/messages'
    | '/lifers/room'
    | '/admin/'
    | '/lifers/'
    | '/ape-rides/$rideId'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/activity'
    | '/lobby'
    | '/profile'
    | '/super-admin'
    | '/support'
    | '/ape-rides'
    | '/calendar'
    | '/feed'
    | '/rooms'
    | '/admin/karaoke'
    | '/admin/lumina'
    | '/admin/otherpage'
    | '/admin/support'
    | '/admin/users'
    | '/lifers/messages'
    | '/lifers/room'
    | '/admin'
    | '/lifers'
    | '/ape-rides/$rideId'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/diagnostics'
    | '/login'
    | '/_authenticated/_verified'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/lifers'
    | '/_authenticated/lobby'
    | '/_authenticated/profile'
    | '/_authenticated/super-admin'
    | '/_authenticated/support'
    | '/_authenticated/_verified/ape-rides'
    | '/_authenticated/_verified/calendar'
    | '/_authenticated/_verified/feed'
    | '/_authenticated/_verified/rooms'
    | '/_authenticated/admin/karaoke'
    | '/_authenticated/admin/lumina'
    | '/_authenticated/admin/otherpage'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/lifers/messages'
    | '/_authenticated/lifers/room'
    | '/_authenticated/admin/'
    | '/_authenticated/lifers/'
    | '/_authenticated/_verified/ape-rides/$rideId'
    | '/_authenticated/_verified/rooms_/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DiagnosticsRoute: typeof DiagnosticsRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lobby': {
      id: '/_authenticated/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof AuthenticatedLobbyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lifers': {
      id: '/_authenticated/lifers'
      path: '/lifers'
      fullPath: '/lifers'
      preLoaderRoute: typeof AuthenticatedLifersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_verified': {
      id: '/_authenticated/_verified'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedVerifiedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lifers/': {
      id: '/_authenticated/lifers/'
      path: '/'
      fullPath: '/lifers/'
      preLoaderRoute: typeof AuthenticatedLifersIndexRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/lifers/room': {
      id: '/_authenticated/lifers/room'
      path: '/room'
      fullPath: '/lifers/room'
      preLoaderRoute: typeof AuthenticatedLifersRoomRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/lifers/messages': {
      id: '/_authenticated/lifers/messages'
      path: '/messages'
      fullPath: '/lifers/messages'
      preLoaderRoute: typeof AuthenticatedLifersMessagesRouteImport
      parentRoute: typeof AuthenticatedLifersRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/otherpage': {
      id: '/_authenticated/admin/otherpage'
      path: '/otherpage'
      fullPath: '/admin/otherpage'
      preLoaderRoute: typeof AuthenticatedAdminOtherpageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lumina': {
      id: '/_authenticated/admin/lumina'
      path: '/lumina'
      fullPath: '/admin/lumina'
      preLoaderRoute: typeof AuthenticatedAdminLuminaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/karaoke': {
      id: '/_authenticated/admin/karaoke'
      path: '/karaoke'
      fullPath: '/admin/karaoke'
      preLoaderRoute: typeof AuthenticatedAdminKaraokeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_verified/rooms': {
      id: '/_authenticated/_verified/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedVerifiedRoomsRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/feed': {
      id: '/_authenticated/_verified/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedVerifiedFeedRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/calendar': {
      id: '/_authenticated/_verified/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedVerifiedCalendarRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/ape-rides': {
      id: '/_authenticated/_verified/ape-rides'
      path: '/ape-rides'
      fullPath: '/ape-rides'
      preLoaderRoute: typeof AuthenticatedVerifiedApeRidesRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/rooms_/$roomId': {
      id: '/_authenticated/_verified/rooms_/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedVerifiedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedVerifiedRoute
    }
    '/_authenticated/_verified/ape-rides/$rideId': {
      id: '/_authenticated/_verified/ape-rides/$rideId'
      path: '/$rideId'
      fullPath: '/ape-rides/$rideId'
      preLoaderRoute: typeof AuthenticatedVerifiedApeRidesRideIdRouteImport
      parentRoute: typeof AuthenticatedVerifiedApeRidesRoute
    }
  }
}

interface AuthenticatedVerifiedApeRidesRouteChildren {
  AuthenticatedVerifiedApeRidesRideIdRoute: typeof AuthenticatedVerifiedApeRidesRideIdRoute
}

const AuthenticatedVerifiedApeRidesRouteChildren: AuthenticatedVerifiedApeRidesRouteChildren =
  {
    AuthenticatedVerifiedApeRidesRideIdRoute:
      AuthenticatedVerifiedApeRidesRideIdRoute,
  }

const AuthenticatedVerifiedApeRidesRouteWithChildren =
  AuthenticatedVerifiedApeRidesRoute._addFileChildren(
    AuthenticatedVerifiedApeRidesRouteChildren,
  )

interface AuthenticatedVerifiedRouteChildren {
  AuthenticatedVerifiedApeRidesRoute: typeof AuthenticatedVerifiedApeRidesRouteWithChildren
  AuthenticatedVerifiedCalendarRoute: typeof AuthenticatedVerifiedCalendarRoute
  AuthenticatedVerifiedFeedRoute: typeof AuthenticatedVerifiedFeedRoute
  AuthenticatedVerifiedRoomsRoute: typeof AuthenticatedVerifiedRoomsRoute
  AuthenticatedVerifiedRoomsRoomIdRoute: typeof AuthenticatedVerifiedRoomsRoomIdRoute
}

const AuthenticatedVerifiedRouteChildren: AuthenticatedVerifiedRouteChildren = {
  AuthenticatedVerifiedApeRidesRoute:
    AuthenticatedVerifiedApeRidesRouteWithChildren,
  AuthenticatedVerifiedCalendarRoute: AuthenticatedVerifiedCalendarRoute,
  AuthenticatedVerifiedFeedRoute: AuthenticatedVerifiedFeedRoute,
  AuthenticatedVerifiedRoomsRoute: AuthenticatedVerifiedRoomsRoute,
  AuthenticatedVerifiedRoomsRoomIdRoute: AuthenticatedVerifiedRoomsRoomIdRoute,
}

const AuthenticatedVerifiedRouteWithChildren =
  AuthenticatedVerifiedRoute._addFileChildren(
    AuthenticatedVerifiedRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKaraokeRoute: typeof AuthenticatedAdminKaraokeRoute
  AuthenticatedAdminLuminaRoute: typeof AuthenticatedAdminLuminaRoute
  AuthenticatedAdminOtherpageRoute: typeof AuthenticatedAdminOtherpageRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKaraokeRoute: AuthenticatedAdminKaraokeRoute,
  AuthenticatedAdminLuminaRoute: AuthenticatedAdminLuminaRoute,
  AuthenticatedAdminOtherpageRoute: AuthenticatedAdminOtherpageRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLifersRouteChildren {
  AuthenticatedLifersMessagesRoute: typeof AuthenticatedLifersMessagesRoute
  AuthenticatedLifersRoomRoute: typeof AuthenticatedLifersRoomRoute
  AuthenticatedLifersIndexRoute: typeof AuthenticatedLifersIndexRoute
}

const AuthenticatedLifersRouteChildren: AuthenticatedLifersRouteChildren = {
  AuthenticatedLifersMessagesRoute: AuthenticatedLifersMessagesRoute,
  AuthenticatedLifersRoomRoute: AuthenticatedLifersRoomRoute,
  AuthenticatedLifersIndexRoute: AuthenticatedLifersIndexRoute,
}

const AuthenticatedLifersRouteWithChildren =
  AuthenticatedLifersRoute._addFileChildren(AuthenticatedLifersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedVerifiedRoute: typeof AuthenticatedVerifiedRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLifersRoute: typeof AuthenticatedLifersRouteWithChildren
  AuthenticatedLobbyRoute: typeof AuthenticatedLobbyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedVerifiedRoute: AuthenticatedVerifiedRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLifersRoute: AuthenticatedLifersRouteWithChildren,
  AuthenticatedLobbyRoute: AuthenticatedLobbyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DiagnosticsRoute: DiagnosticsRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
